services:
  db:
    image: postgres:17.1-alpine
    container_name: company_service_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    networks:
      - company_service
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: company_service
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "127.0.0.1${SERVER_PORT}${SERVER_PORT}"
    networks:
      - company_service
    volumes:
      - .:/app

networks:
  company_service:
    driver: bridge